import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsArrowUpRight} from "react-icons/bs"
import Aos from 'aos'
import Login from '../component/Login'
import 'aos/dist/aos.css' 
import { useEffect, useState } from 'react'

export default function Home() {
  const [open, setOpen] = useState(false)
  useEffect(() =>{
    Aos.init({duration: 2000});
}, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <div className={styles.header} data-aos="fade-right">
             <div className={styles.round}>   
                  <div className={styles.rounded1}></div>
                  <div className={styles.rounded2}></div>
            </div> 
            <h1>umwella</h1>
       </div>
          {open ?<Login closeModal={setOpen}/>:""}
          
      <div className={styles.main}>
        <h1>We are launching</h1>
        <h1>soon</h1>
        <p>if you urgently need a personalised meal plan,</p>
        <button onClick={()=>{
          setOpen(!open)
        }}>Reach out to us <BsArrowUpRight style={{backgroundColor: "orangered"}}/></button>
       </div>

       <div className={styles.meal}>
         <Image
         width={1300}
         style={{color:"red"}}
         height={400}
         src='/mil.png' alt='/'/>
       </div>
{/* 
       <div className={styles.contain} style={{display: open ? "none": ""}}>
         <div className={styles.circle}>
          <div className={styles.image1}>
          <Image
          width={150}
          height={150}
          
          src="/meal1.jpg"/>
          </div>
          <div className={styles.image2}>
          <Image
          width={150}
          height={150}
          
          src="/meal2.jpg"/>
          </div>
          <div className={styles.image3}>
          <Image
          width={150}
          height={150}
          
          src="/meal4.jpg"/>
          </div>
         </div>
       </div> */}
    </div>
  )
}
